/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm2;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Manish PC
 */
public class Withdrawal extends javax.swing.JFrame {
    private final String acc;
    /**
     * Creates new form Withdrawal
     * @param acc_no
     */
    public Withdrawal(String acc_no) {
        initComponents();
        this.acc=acc_no;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Transaction");

        jLabel2.setText("Enter the amount:");

        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });

        jButton1.setText("Withdraw");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Other Options");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton1)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(55, 55, 55)
                .addComponent(jButton2)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String amt = jTextField1.getText();
        int amount = Integer.parseInt(amt);
        String bal =  balance(acc);
        int balance = Integer.parseInt(bal);
        System.out.println(bal);
        System.out.println(amount);
        
        
        
        if( balance > amount){
                // JOptionPane.showMessageDialog(null, "Correct Login Credentials");
              // int ba = balance - amount ;
               int ba = balance - amount ;
               
               String bala = Integer.toString(ba);
                String ub = update(acc,bala);
                 System.out.println(ub);
               //String bala = Integer.toString(ba);
               // String ub = update(acc,bala);
               // int update = Integer.parseInt(ub);
               // System.out.println(update);
               
                //System.out.println(ub);
               
                 End fr = new End();
                 fr.setVisible(true);}
        else{
            JOptionPane.showMessageDialog(null, "Insufficient balance");}
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Other_Options fr = new Other_Options(acc);
        fr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1PropertyChange

    /**
     * @param args the command line arguments
     */
    private String balance(String acc) {
        //ResultSet rs = null;
        try{           
       Class.forName("org.apache.derby.jdbc.EmbeddedDriver");  //  database connection
       Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Atm", "root", "root");    
       PreparedStatement pst = con.prepareStatement("Select balance from account where acc_no=?");
       pst.setString(1, acc); 
      System.out.println(pst);
     
        ResultSet rs = pst.executeQuery();  
        
        if(rs.next()) { 
            return rs.getString(1);
         
        }
           
                  
   }
   catch(Exception e){
       
      
   }       
       return null;
   
}

    
    
 private String update(String acc,String bala) {
        //ResultSet rs = null;
        try{           
       Class.forName("org.apache.derby.jdbc.EmbeddedDriver");  //  database connection
       Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Atm", "root", "root");    
       String sql = (" Update account set balance = "+bala +"  where acc_no= "+acc);
       Statement stmt = con.createStatement();
       
       //stmt.setString(1, bala);
      // stmt.setString(2, acc);
        stmt.executeUpdate(sql);
        System.out.println(stmt);
       //pst.setString(1, bala);
      // pst.setString(1, acc);
       
       PreparedStatement ps = con.prepareStatement("Select balance from account where acc_no=?");
       ps.setString(1, acc);
       
      System.out.println(ps);
      
       //rs = pst.executeQuery();                        
        //return rs.getString(1);
       ResultSet rs = ps.executeQuery();  
        //return rs.getString(1);
        if(rs.next()) { 
            return rs.getString(1);
        //int bal = rs.getInt("balance"); 
        }
           
                  
   }
   catch(Exception e){
       
       //return false;
   }       
       return null;
   
}
    
    
    /*public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdrawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdrawal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
